name: CI

on:
  push:
    branches: [main]
    tags-ignore: ["v?[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm lint

      - name: Package extension
        uses: haaleo/publish-vscode-extension@v1
        with:
          pat: _
          dependencies: false
          dryRun: true
